### ISSUE TITLE
date not updated after user deleting manually input field on browser

### ISSUE THREAD

**Issue by tcastelli** [notorii/meteor-autoform-datetimepicker#3]
I've found out that on desktop, when users remove the date using the keyboard, the date value is not recomputed, so if you introduce one date correctly and then remove it, this.value still remembers the old value and causes errors.

One possible solution (this is what im using right now), is to ensure to attach the class autoform-datetimepicker-input to all the input fields(right now if you define class on the aquickfield it overwrites dateimpicker class) and then on the "change" event add an else clause to check if the value is correct.
This is what I'm using right now, but I'm sure it could be more elegant :P

```javascript

1°) 
<input type="text" value="{{this.value}}" {{atts}}  />

2°)
Session.setTemp(sessKeys.classes, {input:"autoform-datetimepicker-input " });
....
 if(self.featureDetect({}).deviceType ==='ios') {
            var classes1 =Session.get(sessKeys.classes);
            classes1.input = classes1.input + 'ios ';
            Session.setTemp(sessKeys.classes, classes1);
        }
3°)
Template.afDatetimepicker.rendered =function() {
    var elm =this.find('input');
    var key =this.data.atts['data-schema-key'];
    afDatetimepicker.setup(key, elm, this, {});
    var sessKeys =afDatetimepicker.formSessKeys(key, {});
    var classes1 =Session.get(sessKeys.classes);
    $(elm).addClass(classes1.input);
};

4°)
else{           
   var date =evt.target.value;
            if (!moment(evt.target.value).isValid()) {
                var instid = template.data.atts['data-schema-key'];
                VAL[instid] = null;
            }
 }
```

**Comment by lukemadera** [comment]
Thanks @tcastelli - sorry it took awhile to get to these but both are good suggestions and I added fixes accordingly!
