### ISSUE TITLE
Date Time not showing up in Autoform

### ISSUE THREAD

**Issue by a-db** [notorii/meteor-autoform-datetimepicker#4]
The values are passed along but nothing displays when you pick a Date/Time. Check your demo. This is desktop only. Mobile is working fine.

**Comment by csiszi** [comment]
The same problem. It works when it's only Date (without Time). Tested on OSX10.10.4 / Safari 8.0.7 and Chrome 44.0.2403.125

**Comment by lukemadera** [comment]
Thanks for pointing this out @a-db and @csiszi - apologies for the slow reply; this was due to this moment change: https://github.com/moment/moment/issues/1407 and should be fixed now.
