### ISSUE TITLE
pickers with time not working

### ISSUE THREAD

**Issue by mala23** [notorii/meteor-autoform-datetimepicker#5]
Hi there
the picker does not work when a time is required. Same for the demo.
cheers

**Comment by lukemadera** [comment]
Ahh, yikes. Thanks for pointing that out. I'm swamped today but will take a look tonight or tomorrow!

**Comment by mala23** [comment]
Awesome! And you are welcome =)
Worked with Pikaday for now – but will take a look back on your package.

**Comment by lukemadera** [comment]
Unfortunately didn't make it to this and I'll be out of town for the next 5 days so won't be able to fix this until I get back. But will do shortly thereafter!

**Comment by lukemadera** [comment]
Seems to be resolved by meteor package updates. Demo updated and working now.
