### ISSUE TITLE
Safari Invalid Date format

### ISSUE THREAD

**Issue by ynt** [notorii/meteor-autoform-datetimepicker#6]
Got issue with this package when trying to save AutoForm in Safari (9.0.1):

> *date* must be a Date

`formatValue` or `pikaday.format` is not set.

**Comment by ynt** [comment]
Solved with `formatValue: 'YYYY-MM-DDTHH:mm:ssZ'`.

**Comment by lukemadera** [comment]
Ah, interesting, glad you got it figured out and thanks for sharing the fix!
